[package]
name = "abi"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
[dependencies]
tonic = "0.13"
prost = "0.13"
prost-types = "0.13"
[build-dependencies]
tonic-build = {version = "0.13", features = ["prost"]}
